### ISSUE TITLE
运行不起来，报如下错误

### ISSUE THREAD

**Issue by Lixianshengchao** [ansen666/JniTest#1]
$ adb shell am start -n "com.ansen.jnitest/com.ansen.jnitest.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 2946 on device 'genymotion-samsung-192.168.102.101:5555'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ansen.jnitest, PID: 2946
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.ansen.jnitest-1/lib/arm/libmylib.so" has unexpected e_machine: 40
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.ansen.jnitest.MainActivity.<clinit>(MainActivity.java:22)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2538)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ansen666** [comment]
代表重新提交了，你拉最新代码试试。
